blank_issues_enabled: false
contact_links:
  - name: 📚 Help Documentation
    url: https://inspection-form-buil-ulq6.bolt.host/help
    about: Check our comprehensive help center first
  - name: 🚀 Live Demo
    url: https://inspection-form-buil-ulq6.bolt.host
    about: Try InspectPro live in your browser